development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: khf_dev
  pool: 5
  username: khf_dev
  password: zxcvbn
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: khf_test
  pool: 5
  username: khf_test
  password: zxcvbn
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: khf
  pool: 5
  username: khf
  password: zxcvbn
  socket: /var/run/mysqld/mysqld.sock
